syntax = "proto3";

// Bổ sung định nghĩa package Protobuf
package order;

option java_multiple_files = true;
option java_package = "com.example.grpc";

// Định nghĩa Service (Interface)
service OrderService {
  rpc CreateOrder (CartRequest) returns (OrderResponse);
}

// Định nghĩa Message (Data Structures)
message CartRequest {
  int32 userId = 1;
  repeated CartItem items = 2;
  DeliveryAddress address = 3;
}

message CartItem {
  string id = 1;
  string name = 2;
  double price = 3;
  int32 quantity = 4;
  string image = 5;

  string variantId = 6;   // optional
}

message DeliveryAddress {
  string recipientName = 1;
  string phoneNumber = 2;
  string country = 3;
  string province = 4;
  string city = 5;
  string locationDetail = 6;
}

message OrderResponse {
  string orderId = 1;
  string message = 2;
}